version: "3.4"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: husks
      POSTGRES_PASSWORD: husks
      POSTGRES_DB: husks
    ports:
      - 5432:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "25:25"

  chatglm:
    image: peakji92/chatglm:6b
    ports:
      - "3001:80"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # that's the closest analogue to --gpus; provide
              # an integer amount of devices or 'all'
              count: 1
              # Devices are reserved using a list of capabilities, making
              # capabilities the only required field. A device MUST
              # satisfy all the requested capabilities for a successful
              # reservation.
              capabilities: [gpu]

volumes:
  # postgresql:
  local_postgres_data:
