version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  husks_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: husks_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env.production
    ports:
      - "5433:5432"

  urpics_prisma_studio:
    <<: *urpics_frontend
    image: urpics_prisma_studio
    command: sh -c "npx --yes prisma studio --port 5555 --schema=./prisma/schema.prisma"
    ports:
      - "5555:5555"

  husks_frontend: &husks_frontend
    image: husks_production_frontend
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile

    # depends_on:
    #   - postgres
    restart: on-failure
    env_file:
      - .env

    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
