version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  images: {}

services:
  husks_postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: husks_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env.production

  husks_frontend: &husks_frontend
    image: husks_production_frontend
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile

    depends_on:
      - husks_postgres
    restart: on-failure
    env_file:
      - .env

    networks:
      - traefik_proxy
      - default

  husks_prisma_studio:
    <<: *husks_frontend
    image: urpics_prisma_studio
    command: sh -c "npx --yes prisma studio --port 5555 --schema=./prisma/schema.prisma"
    ports:
      - "5556:5555"

    networks:
      - default
      - traefik_proxy
  imaginary:
    image: h2non/imaginary:latest
    volumes:
      - images:/mnt/data
    environment:
      - PORT=3001

    command: -enable-url-source -mount /mnt/data -cors -gzip --http-cache-ttl 604800
    networks:
      - default
      - traefik_proxy
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "0.1"
          memory: 50M
    restart: always
networks:
  traefik_proxy:
    external: true
