log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    # http:
    #   # https://docs.traefik.io/routing/entrypoints/#entrypoint
    #   redirections:
    #     entryPoint:
    #       to: web-secure

  web-secure:
    # https
    address: ":443"

# certificatesResolvers:
#   letsencrypt:
#     # https://docs.traefik.io/master/https/acme/#lets-encrypt
#     acme:
#       email: "mesmer@mail.com"
#       storage: /etc/traefik/acme/acme.json
#       # https://docs.traefik.io/master/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web
#       dnsChallenge:
#         provider: cloudflare

http:
  routers:
    web-secure-urpics-frontend:
      rule: "Host(`urpics.art`) || Host(`www.urpics.art`)"
      entryPoints:
        - web
      middlewares:
        - csrf
        - test-compress
      service: urpics_frontend
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt

    web-secure-img-resize-frontend:
      rule: "Host(`husks.org`) || Host(`www.husks.org`) && PathPrefix(`/resize`)"
      entryPoints:
        - web
      middlewares:
        - test-compress
      service: imaginary
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt

    web-secure-husks-frontend:
      rule: "Host(`husks.org`) || Host(`www.husks.org`) && !PathPrefix(`/resize`)"
      entryPoints:
        - web
      middlewares:
        - csrf
        - test-compress
      service: husks_frontend
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt

    web-secure-styleqr-frontend:
      rule: "Host(`aieasypic.com`) || Host(`www.aieasypic.com`)"
      entryPoints:
        - web
      middlewares:
        - csrf
        - test-compress
      service: styleqr_frontend
      # tls:
      #   # https://docs.traefik.io/master/routing/routers/#certresolver
      #   certResolver: letsencrypt
  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    test-compress:
      compress:
        excludedContentTypes:
          - text/event-stream

  services:
    urpics_frontend:
      loadBalancer:
        servers:
          - url: http://urpics_frontend:3000

    husks_frontend:
      loadBalancer:
        servers:
          - url: http://husks_frontend:3000

    styleqr_frontend:
      loadBalancer:
        servers:
          - url: http://styleqr_frontend:3000

    imaginary:
      loadBalancer:
        servers:
          - url: http://imaginary:9000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
labels:
  - "traefik.http.routers.web-secure-router.middlewares=traefik-compress"
  - "traefik.http.middlewares.traefik-compress.compress=true"
