version: "3"

volumes:
  production_traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: husks_production_traefik
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
